version: '3.8'

services:
  postgres-db:
    image: postgres:17  # PostgreSQL 17 image
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task_management_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  task-service:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/azhar467/task-management-service:latest
    container_name: task-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/task_management_service
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
