global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'task-management-service'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/task-management-service/actuator/prometheus'
    scrape_interval: 5s