name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.actor != 'local-profile'  # Exclude local profile
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Set up JDK 17 for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build with Maven and run tests with coverage
      - name: Build with Maven
        run: mvn clean install -Pcoverage

      # Step 4: Verify the JAR exists
      - name: Verify JAR exists
        run: ls target/

      # Step 5: Upload the JAR as an artifact to be used in the next job
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: task-management-service-jar
          path: target/task-management-service-0.0.1-SNAPSHOT.jar