name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master  # or the branch you're pushing to

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}  # Make sure this secret is set

      - name: Build Docker image
        run: |
          docker build -t your-repository-name .

      - name: Tag Docker image
        run: |
          docker tag your-repository-name:latest your-account-id.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/your-repository-name:latest

      - name: Push Docker image to ECR
        run: |
          docker push your-account-id.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/your-repository-name:latest
