name: Build, SonarQube Analysis, and Push Docker Image to ECR

on:
  push:
    branches:
      - master

jobs:
  # Stage 1: Build
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Set up JDK 17 for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build with Maven (Clean Install)
      - name: Build with Maven (Clean Install)
        run: mvn clean install

      # Step 4: Build with Maven (Clean Package)
      - name: Build with Maven (Clean Package)
        run: mvn clean package

  # Stage 2: SonarQube Analysis
  sonar:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Set up JDK 17 for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: SonarQube Scan
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # SonarQube token from secrets
        run: mvn sonar:sonar \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  # Stage 3: Docker Build and Push
  docker:
    runs-on: ubuntu-latest
    needs: sonar  # This job depends on the sonar job

    steps:
      # Step 1: Configure AWS Credentials for ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 2: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t azhar467/task-management-service:latest .

      # Step 3: Login to ECR
      - name: Login to ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 789761962952.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # Step 4: Tag and Push Docker Image to ECR
      - name: Push Docker Image to ECR
        run: |
          docker tag azhar467/task-management-service:latest 789761962952.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/azhar467/task-management-service:latest
          docker push 789761962952.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/azhar467/task-management-service:latest
