name: Build, SonarQube Analysis, and Push Docker Image to ECR

on:
  push:
    branches:
      - master

jobs:
  build-analyze-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Set up JDK 17 for Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build with Maven (Clean Install)
      - name: Build with Maven (Clean Install)
        run: mvn clean install

      # Step 4: Display Maven Build Output (optional)
      - name: Display Maven Output
        run: cat target/maven-build.log

      # Step 5: SonarQube Code Quality Analysis
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # SonarQube token from secrets
        run: mvn sonar:sonar \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -X  # (optional: for detailed logs)

      # Step 6: Display SonarQube Analysis Output (optional)
      - name: Display SonarQube Output
        run: cat target/sonar/sonar-results.txt

      # Step 7: Build with Maven (Clean Package)
      - name: Build with Maven (Clean Package)
        run: mvn clean package

      # Step 8: Configure AWS Credentials for ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 9: Build Docker Image
      - name: Build Docker Image
        run: docker build -t azhar467/task-management-service:latest .

      # Step 10: Login to ECR (once before building Docker image)
      - name: Login to ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 789761962952.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # Step 11: Push Docker Image to ECR
      - name: Push Docker Image to ECR
        run: docker push 789761962952.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/azhar467/task-management-service:latest
