name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Debug AWS Region
        run: |
          echo "AWS Region: ${{ secrets.AWS_REGION }}"  # Log AWS region to debug

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}  # Ensure this secret is set correctly
          mask-password: false
          registry-type: private
          skip-logout: false

      - name: Build Docker image
        run: |
          docker build -t task-management-service .

      - name: Tag Docker image
        run: |
          docker tag task-management-service:latest 789761962952.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/azhar467/task-management-service:latest

      - name: Push Docker image to ECR
        run: |
          docker push 789761962952.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/azhar467/task-management-service:latest
